entrada = input ()
valores = entrada.split ()
print (valores)
matricula = int(valores[0])
print ('matricula',matricula)
nota1 = float(valores[1])
print('nota1',nota1)
nota2 = float (valores[2])
print('nota2',nota2)